const http = require("http");
const request = (method, path, body) => new Promise((resolve, reject) => { const payload = body === undefined ? undefined : JSON.stringify(body); const req = http.request({ hostname: "localhost", port: 5000, path, method, headers: payload ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) } : {} }, (res) => { let data = ""; res.on("data", (chunk) => { data += chunk; }); res.on("end", () => resolve(res.statusCode)); }); req.on("error", reject); if (payload) req.write(payload); req.end(); });
const routes = [
  ["GET", "/api/v1/health", undefined, 200],
  ["POST", "/api/auth/register", {}, 400], ["POST", "/api/auth/provider-register", {}, 400], ["POST", "/api/auth/login", {}, 400], ["GET", "/api/auth/me", undefined, 401],
  ["GET", "/api/users", undefined, 401], ["GET", "/api/users/1", undefined, 401], ["POST", "/api/users", {}, 401], ["PATCH", "/api/users/1", {}, 401], ["PATCH", "/api/users/1/status", {}, 401], ["DELETE", "/api/users/1", undefined, 401],
  ["GET", "/api/providers", undefined, 401], ["GET", "/api/providers/me", undefined, 401], ["PATCH", "/api/providers/me", {}, 401], ["GET", "/api/providers/1", undefined, 401], ["POST", "/api/providers", {}, 401], ["PATCH", "/api/providers/1", {}, 401], ["PATCH", "/api/providers/1/status", {}, 401], ["PATCH", "/api/providers/1/kyc", {}, 401],
  ["POST", "/api/providers/kyc", {}, 401], ["GET", "/api/providers/kyc", undefined, 401], ["GET", "/api/admin/kyc", undefined, 401], ["PATCH", "/api/admin/kyc/1/review", {}, 401],
  ["GET", "/api/v1/provider/services", undefined, 401], ["GET", "/api/v1/provider/services/1", undefined, 401], ["POST", "/api/v1/provider/services", {}, 401], ["PATCH", "/api/v1/provider/services/1", {}, 401], ["DELETE", "/api/v1/provider/services/1", undefined, 401],
  ["GET", "/api/v1/provider/services/1/plans", undefined, 401], ["POST", "/api/v1/provider/services/1/plans", {}, 401], ["PATCH", "/api/v1/provider/services/1/plans/1", {}, 401], ["DELETE", "/api/v1/provider/services/1/plans/1", undefined, 401],
  ["GET", "/api/v1/provider/service-areas", undefined, 401], ["POST", "/api/v1/provider/service-areas", {}, 401], ["PATCH", "/api/v1/provider/service-areas/1", {}, 401], ["DELETE", "/api/v1/provider/service-areas/1", undefined, 401],
  ["GET", "/api/providers/availability", undefined, 401], ["POST", "/api/providers/availability", {}, 401], ["PATCH", "/api/providers/availability/1", {}, 401], ["DELETE", "/api/providers/availability/1", undefined, 401], ["GET", "/api/providers/1/availability?date=2026-08-21", undefined, 401],
  ["GET", "/api/providers/bank-account", undefined, 401], ["POST", "/api/providers/bank-account", {}, 401], ["PATCH", "/api/providers/bank-account", {}, 401], ["DELETE", "/api/providers/bank-account", undefined, 401],
  ["GET", "/api/providers/expenses", undefined, 401], ["GET", "/api/providers/expenses/1", undefined, 401], ["POST", "/api/providers/expenses", {}, 401], ["PATCH", "/api/providers/expenses/1", {}, 401], ["DELETE", "/api/providers/expenses/1", undefined, 401],
  ["GET", "/api/providers/accounting/summary", undefined, 401], ["GET", "/api/providers/settlements", undefined, 401], ["GET", "/api/providers/settlements/1", undefined, 401], ["POST", "/api/providers/settlements", {}, 401],
  ["GET", "/api/orders", undefined, 401], ["POST", "/api/orders", {}, 401], ["GET", "/api/orders/1", undefined, 401], ["PATCH", "/api/orders/1/status", {}, 401],
  ["GET", "/api/reviews/1", undefined, 401], ["POST", "/api/reviews", {}, 401], ["GET", "/api/notifications", undefined, 401], ["GET", "/api/notifications/unread-count", undefined, 401], ["PATCH", "/api/notifications/read-all", undefined, 401], ["PATCH", "/api/notifications/1/read", undefined, 401],
  ["GET", "/api/addresses", undefined, 401], ["POST", "/api/addresses", {}, 401], ["PATCH", "/api/addresses/1", {}, 401], ["DELETE", "/api/addresses/1", undefined, 401],
  ["GET", "/api/subscriptions", undefined, 401], ["POST", "/api/subscriptions", {}, 401], ["GET", "/api/subscriptions/1", undefined, 401], ["PATCH", "/api/subscriptions/1", {}, 401], ["GET", "/api/subscriptions/1/deliveries", undefined, 401], ["POST", "/api/subscriptions/1/skip", {}, 401],
  ["GET", "/api/support/tickets", undefined, 401], ["POST", "/api/support/tickets", {}, 401], ["GET", "/api/support/tickets/1", undefined, 401], ["POST", "/api/support/tickets/1/messages", {}, 401], ["PATCH", "/api/support/tickets/1", {}, 401],
  ["GET", "/api/catalog/services", undefined, 200], ["GET", "/api/catalog/services/1", undefined, [200, 404]], ["GET", "/api/catalog/categories", undefined, 200], ["GET", "/api/catalog/providers", undefined, 200],
  ["GET", "/api/admin/categories", undefined, 401], ["POST", "/api/admin/categories", {}, 401], ["PATCH", "/api/admin/categories/1", {}, 401], ["DELETE", "/api/admin/categories/1", undefined, 401], ["GET", "/api/admin/stats", undefined, 401],
  ["GET", "/api/admin/services", undefined, 401], ["PATCH", "/api/admin/services/1/moderation", {}, 401], ["GET", "/api/admin/service-areas", undefined, 401], ["PATCH", "/api/admin/service-areas/1", {}, 401], ["GET", "/api/admin/reports", undefined, 401], ["GET", "/api/admin/audit-logs", undefined, 401], ["GET", "/api/admin/commission-rules", undefined, 401], ["POST", "/api/admin/commission-rules", {}, 401], ["GET", "/api/admin/settlements", undefined, 401], ["PATCH", "/api/admin/settlements/1", {}, 401], ["POST", "/api/admin/refunds/1", {}, 401], ["GET", "/api/customers/wallet", undefined, 401], ["GET", "/api/customers/wallet/transactions", undefined, 401], ["GET", "/api/invoices", undefined, 401], ["GET", "/api/invoices/1/pdf", undefined, 401], ["POST", "/api/coupons/validate", {}, 401], ["POST", "/api/coupons/apply", {}, 401], ["POST", "/api/v1/subscriptions/run-scheduler", {}, 401],
  ["POST", "/api/payments/orders", {}, 401], ["POST", "/api/payments/verify", {}, 401], ["POST", "/api/payments/1/refund", {}, 401], ["POST", "/api/payments/webhook", {}, 503],
];
(async () => { const results = []; for (const [method, path, body, expected] of routes) { const status = await request(method, path, body); results.push({ method, path, expected, status, pass: Array.isArray(expected) ? expected.includes(status) : status === expected }); } const failed = results.filter((item) => !item.pass); console.log(JSON.stringify({ totalRoutes: routes.length, passed: routes.length - failed.length, failed: failed.length, failures: failed }, null, 2)); process.exitCode = failed.length ? 1 : 0; })().catch((error) => { console.error(error); process.exitCode = 2; });
