const express = require("express");
const controller = require("../controllers/adminPlatform.controller");
const authenticate = require("../midleware/auth");
const authorize = require("../midleware/authorize");
const validate = require("../midleware/validate");
const schemas = require("../validators/admin.validator");
const paymentSchemas = require("../validators/payment.validator");
const router = express.Router();
router.use(authenticate, authorize(1));
router.get("/categories", controller.listCategories);
router.post("/categories", validate(schemas.category), controller.createCategory);
router.patch("/categories/:id", validate({ ...schemas.params, body: schemas.categoryUpdate }), controller.updateCategory);
router.delete("/categories/:id", validate(schemas.params), controller.deleteCategory);
router.get("/stats", controller.stats);
router.get("/settings", controller.listSettings);
router.get("/settings/:key", controller.getSetting);
router.patch("/settings/:key", validate(schemas.settingUpdate), controller.updateSetting);
router.get("/coupons", controller.listCoupons);
router.post("/coupons", validate(schemas.coupon), controller.createCoupon);
router.patch("/coupons/:id", validate({ ...schemas.params, body: schemas.couponUpdate }), controller.updateCoupon);
router.get("/reports", controller.reports);
router.get("/reports/revenue", validate(schemas.reportingQuery), controller.report("revenue"));
router.get("/reports/orders", validate(schemas.reportingQuery), controller.report("orders"));
router.get("/reports/providers", validate(schemas.reportingQuery), controller.report("providers"));
router.get("/reports/customers", validate(schemas.reportingQuery), controller.report("customers"));
router.get("/reports/subscriptions", validate(schemas.reportingQuery), controller.report("subscriptions"));
router.get("/reports/expenses", validate(schemas.reportingQuery), controller.report("expenses"));
router.get("/orders", validate(schemas.reportingQuery), controller.monitoring("orders"));
router.get("/subscriptions", validate(schemas.reportingQuery), controller.monitoring("subscriptions"));
router.get("/deliveries", validate(schemas.reportingQuery), controller.monitoring("deliveries"));
router.get("/services", controller.listServices);
router.patch("/services/:id/moderation", validate({ ...schemas.params, body: schemas.moderation }), controller.moderateService);
router.get("/service-areas", controller.listServiceAreas);
router.patch("/service-areas/:id", controller.updateServiceArea);
router.get("/audit-logs", controller.auditLogs);
router.get("/commission-rules", controller.listCommissionRules);
router.post("/commission-rules", validate(schemas.commissionRule), controller.createCommissionRule);
router.patch("/commission-rules/:id", validate({ ...schemas.params, body: schemas.commissionRule }), controller.updateCommissionRule);
router.get("/settlements", controller.listSettlements);
router.patch("/settlements/:id", validate({ ...schemas.params, body: schemas.settlementUpdate }), controller.updateSettlement);
router.post("/refunds/:paymentId", validate({ params: paymentSchemas.paymentParams.params, body: paymentSchemas.refund }), controller.refund);
module.exports = router;
