const express = require("express");
const controller = require("../controllers/subscription.controller");
const authenticate = require("../midleware/auth");
const authorize = require("../midleware/authorize");
const validate = require("../midleware/validate");
const schemas = require("../validators/subscription.validator");
const router = express.Router();
router.use(authenticate, authorize(2));
router.get("/", controller.list);
router.post("/", validate(schemas.create), controller.create);
router.get("/:id", validate(schemas.params), controller.get);
router.patch("/:id", validate({ ...schemas.params, body: schemas.update }), controller.update);
router.get("/:id/deliveries", validate(schemas.params), controller.deliveries);
router.post("/:id/skip", validate({ ...schemas.params, body: schemas.skip }), controller.skip);
router.post("/:id/pause", validate(schemas.params), controller.pause);
router.post("/:id/resume", validate(schemas.params), controller.resume);
router.post("/:id/cancel", validate(schemas.params), controller.cancel);
router.post("/:id/renew", validate(schemas.params), controller.renew);
router.post("/:id/vacation", validate({ ...schemas.params, body: schemas.vacation }), controller.vacation);
router.get("/:id/calendar", validate({ ...schemas.params, ...schemas.calendar }), controller.calendar);
module.exports = router;
