import { useEffect, useState } from 'react';
import adminService from '../services/admin.service';
import AdminModulePage from './AdminModulePage';

const columns = [
  { label: 'Report', key: 'report' },
  { label: 'Type', key: 'type' },
  { label: 'Generated', key: 'generated_at' },
  { label: 'Status', key: 'status' },
];

export default function AdminReportsPage() {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      try {
        const response = await adminService.getAdminReports();
        const data = response?.rows || response?.data || response || [];
        if (!mounted) return;
        setRows(data || []);
      } catch (loadError) {
        if (mounted) setError(loadError?.message || 'Unable to load reports.');
      } finally {
        if (mounted) setLoading(false);
      }
    };

    load();
    return () => { mounted = false; };
  }, []);

  return (
    <AdminModulePage
      title="Reports"
      subtitle="Operational and financial reports generated by the admin backend."
      columns={columns}
      rows={rows}
      loading={loading}
      error={error}
      emptyTitle="No reports"
      emptyMessage="No report rows were returned by the admin reporting API."
    />
  );
}
